---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: mongos
  name: mongos
spec:
  type: NodePort
  ports:
  - name: "30004"
    port: 27017
    targetPort: 27017
    nodePort: 30004
  selector:
    io.kompose.service: mongos
status:
  loadBalancer: {}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: mongos
  name: mongos
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongos
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: mongos
    spec:
      containers:
      - args:
        - mongos
        - --configdb
        - cfgrs/cfgsvr1:27017,cfgsvr2:27017,cfgsvr3:27017
        - --bind_ip
        - 0.0.0.0
        - --port
        - "27017"
        image: mongo
        imagePullPolicy: ""
        name: mongos
        ports:
        - containerPort: 27017
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
